# Generated by Django 5.1.3 on 2024-11-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='submissions/', verbose_name='Signature Image')),
                ('source', models.CharField(help_text='Source of the signature (e.g., person or organization)', max_length=100, verbose_name='Source')),
                ('label', models.CharField(choices=[('Real', 'Real'), ('Forged', 'Forged')], max_length=10, verbose_name='Prediction Label')),
                ('accuracy', models.FloatField(default=0.0, verbose_name='Prediction Accuracy (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submission Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
        ),
    ]
